// lucide 0.6 (protocol-resources), PEAKUB DX initiative - the codegen half of
// buildProtocolResources(). Turns that scan's output into a `.d.ts` that merges into
// @servable/server's `ServableServiceCallMap` (see that package's own global.d.ts for why that
// interface is declared open there rather than typed fully in one place). Each entry references
// the real service file with `typeof import(path).default` - not a serialized copy of its
// signature - so the generated type can never drift from the live handler: whatever JSDoc that
// file has on its `handler` IS the type, always, by construction.
//
// Jobs are emitted as a plain per-protocol listing (`ServableProtocolJobs`), not merged into any
// call-map, since nothing invokes a job by id - see buildProtocolResources()'s own file for why.

const HEADER = `// AUTO-GENERATED by \`servable schema protocol-types\` - do not hand-edit, it will be
// overwritten on the next run. Regenerate whenever a protocol adds/removes/renames a service or
// job. Commit it alongside servable.schema.json so editors don't need to run the generator to
// get these types.
//
// Every \`typeof import(...)\` below points at the real, live service/job file - the type is
// never a hand-maintained copy of that file's signature, so it can't drift from it.
`

/**
 * @param {string} path - absolute path to a service/job file.
 * @returns {string} a module specifier safe to embed in a `typeof import('...')` type query.
 */
const importSpecifier = path => JSON.stringify(path)

/**
 * @param {import('./index.js').ProtocolResourceEntry} service
 * @returns {string}
 */
const serviceEntryLine = service =>
  `    ${JSON.stringify(service.id)}: typeof import(${importSpecifier(service.path)})['default']`

/**
 * @param {import('./index.js').ProtocolResourceEntry} job
 * @returns {string}
 */
const jobEntryLine = job =>
  `    ${JSON.stringify(job.id)}: typeof import(${importSpecifier(job.path)})['default']`

/**
 * Generates a `.d.ts` that:
 *   - merges every discovered service into `ServableServiceCallMap` (sharpening
 *     `Servable.Services.call({ id, params })`'s `params`/return type for that `id`).
 *   - emits one `ServableProtocolJobs` interface per protocol, keyed by protocol id, listing its
 *     jobs for discoverability (no call-site typing - nothing invokes a job by id).
 *
 * @param {Record<string, import('./index.js').ProtocolResources>} resources - `buildProtocolResources()`'s output.
 * @returns {string} the full `.d.ts` file contents.
 */
export default function generateProtocolResourceTypes(resources) {
  const protocolIds = Object.keys(resources || {}).sort((a, b) => a.localeCompare(b))

  // Deduped by `id`, first occurrence wins - mirrors the real registry's own semantics
  // (domain/servable/services/index.js's `register()` skips a service whose `id`+`version` is
  // already registered), and keeps this from ever emitting a TS interface with a duplicate
  // property name, which would be invalid output.
  const seenServiceIds = new Set()
  const allServices = protocolIds
    .flatMap(protocolId => resources[protocolId].services)
    .sort((a, b) => a.id.localeCompare(b.id))
    .filter(service => {
      if (seenServiceIds.has(service.id)) {
        return false
      }
      seenServiceIds.add(service.id)
      return true
    })

  // Sanitizing a protocol id into an identifier can collide (e.g. `@a/foo-bar` and `@a/foo_bar`
  // both sanitize to `_a_foo_bar`) even though real protocol ids never collide with each other -
  // disambiguated with a numeric suffix rather than risk emitting two interfaces with the same
  // name, which would be invalid output.
  const seenJobInterfaceNames = new Set()
  const jobInterfaces = protocolIds
    .filter(protocolId => resources[protocolId].jobs.length)
    .map(protocolId => {
      const jobs = resources[protocolId].jobs.slice().sort((a, b) => a.id.localeCompare(b.id))
      const jobLines = jobs.map(jobEntryLine).join('\n')
      let safeProtocolName = protocolId.replace(/[^A-Za-z0-9_$]/g, '_')
      let interfaceName = `ServableProtocolJobs_${safeProtocolName}`
      let suffix = 2
      while (seenJobInterfaceNames.has(interfaceName)) {
        interfaceName = `ServableProtocolJobs_${safeProtocolName}_${suffix}`
        suffix += 1
      }
      seenJobInterfaceNames.add(interfaceName)
      return `/** Jobs defined by protocol \`${protocolId}\`. */\n` +
        `export interface ${interfaceName} {\n${jobLines}\n}`
    })
    .join('\n\n')

  // Omitted entirely (rather than merged as an empty/index-signature interface) when there are
  // no services anywhere in the app - @servable/server's own `ServableServiceCallMap` already
  // declares the open, loose-fallback index signature; restating it here would be redundant.
  const serviceMapMerge = allServices.length
    ? `declare global {\n  interface ServableServiceCallMap {\n${allServices.map(serviceEntryLine).join('\n')}\n  }\n}\n`
    : ''

  return [
    HEADER,
    serviceMapMerge,
    jobInterfaces,
    'export {}\n',
  ].filter(Boolean).join('\n')
}
