// lucide (PEAKUB DX initiative) - PEAKUB-321's sibling: `servable.schema.json` already fully
// describes every class and field (that's the whole point of unischema's committed artifact -
// see .docs/technical/unischema-plan.md). This turns that same artifact into a `.d.ts` so
// `object.get('caption')`/`object.set('caption', value)` gets real autocomplete and a typo in a
// field name gets flagged, for every app-specific class - pure codegen, no new modeling effort,
// regenerated fresh on every `servable schema build` (see `servable schema types`, the CLI
// command this backs).

/** Parse field type -> the TS type a getter/setter for it should carry. */
const FIELD_TYPE_MAP = {
  String: 'string',
  Number: 'number',
  Boolean: 'boolean',
  Date: 'Date',
  Array: 'any[]',
  Object: 'Record<string, any>',
  GeoPoint: '{ latitude: number, longitude: number }',
  Polygon: 'Array<[number, number]>',
  File: '{ url: () => string, name: () => string }',
  ACL: 'Record<string, { read?: boolean, write?: boolean }>',
  Relation: 'ServableRelation<any>',
}

/**
 * @param {{ type: string, targetClass?: string }} field
 * @param {Set<string>} knownClassNames - classes the artifact actually defines; a `Pointer`
 *   to anything else (e.g. a core Parse class like `_User` when only app classes were passed
 *   in) falls back to a generic shape rather than referencing a type that won't exist.
 */
const tsTypeForField = (field, knownClassNames) => {
  if (field.type === 'Pointer') {
    return field.targetClass && knownClassNames.has(field.targetClass)
      ? `ServablePointer<${field.targetClass}>`
      : 'ServablePointer<any>'
  }

  return FIELD_TYPE_MAP[field.type] || 'any'
}

const HEADER = `// AUTO-GENERATED by \`servable schema types\` from servable.schema.json - do not hand-edit,
// it will be overwritten on the next \`servable schema build\`. Commit it alongside
// servable.schema.json itself so editors don't need to run the generator to get these types.
//
// Every field is optional: Parse never enforces a field's presence purely from schema (that's
// what CLPs/beforeSave validation are for), so a freshly-fetched or not-yet-saved object may
// legitimately be missing any of them.

/** A Parse Pointer field, narrowed to the class it points at. */
export interface ServablePointer<T> {
  id: string
  className: string
  get<K extends keyof T>(key: K): T[K]
  set<K extends keyof T>(key: K, value: T[K]): this
  fetch(options?: Record<string, any>): Promise<this>
}

/** A Parse Relation field, narrowed to the class it relates to. */
export interface ServableRelation<T> {
  query(): { find(options?: Record<string, any>): Promise<T[]> }
  add(object: T): void
  remove(object: T): void
}
`

/**
 * Generates one TypeScript interface per class in a `servable.schema.json` artifact, each
 * field typed from its Parse field type (`Pointer`/`Relation` narrowed to the target class
 * when that class is also present in the artifact) - plus a merge into
 * @servable/parse-server-engine's `ServableClassMap`, keyed by class name, powering
 * `Servable.App.Typed.object('ClassName')`/`.query('ClassName')` (see that package's own
 * global.d.ts for why that's a separate, opt-in surface rather than a change to `Object`/`Query`
 * themselves).
 *
 * @param {{ classes: Array<{ className: string, fields: Record<string, { type: string, targetClass?: string }> }> }} artifact
 *   - a normalized `servable.schema.json` (or anything with the same `classes` shape).
 * @returns {string} the full `.d.ts` file contents.
 */
export default function generateSchemaTypes(artifact) {
  const classes = artifact?.classes || []
  const knownClassNames = new Set(classes.map(c => c.className))

  const sortedClasses = classes.slice().sort((a, b) => a.className.localeCompare(b.className))

  const interfaces = sortedClasses
    .map(({ className, fields = {} }) => {
      const fieldLines = Object.entries(fields)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([fieldName, field]) => {
          const safeName = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(fieldName)
            ? fieldName
            : JSON.stringify(fieldName)
          return `  ${safeName}?: ${tsTypeForField(field, knownClassNames)}`
        })
        .join('\n')

      return `export interface ${className} {\n${fieldLines || '  [key: string]: any'}\n}`
    })
    .join('\n\n')

  // Omitted entirely (rather than merged as an empty interface) when there are no classes at
  // all - matches generateProtocolResourceTypes()'s own ServableServiceCallMap handling.
  const classMapMerge = sortedClasses.length
    ? `declare global {\n  interface ServableClassMap {\n${sortedClasses
        .map(({ className }) => `    ${JSON.stringify(className)}: ${className}`)
        .join('\n')}\n  }\n}\n`
    : ''

  return [HEADER, interfaces, classMapMerge].filter(Boolean).join('\n')
}
